security:
    password_hashers:
        App\Entity\Register:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Register
                property: username

    firewalls:
        main:
            pattern: ^/
            provider: app_user_provider
            lazy: true
            form_login:
                login_path: admin_login   # page de login unique
                check_path: admin_login
                username_parameter: _username
                password_parameter: _password
                default_target_path: /project
            logout:
                path: /admin/logout
                target: /admin/login

    access_control:
    - { path: ^/project/public, roles:  }
    - { path: ^/project/new$, roles: ROLE_ADMIN }
    - { path: ^/project/\d+/edit$, roles: ROLE_ADMIN }
    - { path: ^/project/\d+/delete$, roles: ROLE_ADMIN }
    - { path: ^/project$, roles: ROLE_ADMIN }
