services:
  db:
    image: postgres:17
    container_name: symfony_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: a.elidrissi
      POSTGRES_PASSWORD: amsom-habitat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
