services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:17
    container_name: symfony_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: a.elidrissi
      POSTGRES_PASSWORD: amsom-habitat
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

